name: PR Comment Hello You

on:
  issue_comment:
    types:
      - created

jobs:
  greet_on_pr_comment:
    if: ${{ github.event.issue.pull_request != null && github.event.comment.body == 'hello you' }}
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "Hello, World! Someone said 'hello you' on a pull request."
