name: 1.6-echo-hello-world-when-specific-comment

on:
  issue_comment:
    types:
      - created # Trigger the workflow on comment creation

jobs:
  echo-hello-world-when-specific-comment:
    if: ${{ github.event.issue.pull_request != null && github.event.comment.body == 'hello you' }}
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "Hello, World! Someone said 'hello you' on a pull request."
