name: 2.1-echo-input-text-with-manual-trigger

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Enter the text to echo'
        required: true
        default: 'Hello, World!'

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Echo the input message
      run: |
        # Store the input message in a Bash variable
        MY_MESSAGE="${{ github.event.inputs.message }}"

        # Echo the message using both the direct reference and the stored variable
        echo "${{ github.event.inputs.message }}"
        echo "$MY_MESSAGE"

        # Echo with a custom message for clarity
        echo "\n\nYou entered: '${{ github.event.inputs.message }}'"
        echo "\n\nYou entered: '$MY_MESSAGE'"
