name: 2.1-echo-input-text-with-manual-trigger

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Enter the text to echo'
        required: true
        default: 'Hello, World!'

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Echo the input message
      run: |
        MY_MESSAGE="${{ github.event.inputs.message }}"
        echo ${{ github.event.inputs.message }}
        echo $MY_MESSAGE
        echo "\n\n You entered '${{ github.event.inputs.message }}'"
        echo "\n\n You entered '${{ MY_MESSAGE }}'"