name: 3.1-echo-context-on-pr

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Enter the text to echo'
        required: true
        default: 'Hello, World!'

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Echo the input message
      run: |
        echo ${{ github }}
