name: 3.1-echo-context-on-pr

on: workflow_dispatch

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Serialize and echo github context
      run: |
        echo '${{ toJson(github) }}' | jq .
