name: 3.1-serializing-data-when-manual-trigger

on: workflow_dispatch

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Serialize and echo github context
      run: |
        echo '${{ toJson(github) }}'
