name: 4.1-echoing-relevant-data-when-specific-comment

on: workflow_dispatch

jobs:
  serializing-data:
    runs-on: ubuntu-latest

    steps:
    - name: Serialize and echo github context
      run: |
        echo '${{ toJson(github) }}'
