name: 4.1-echoing-relevant-data-when-specific-comment

on:
  issue_comment: 
    types:
      - created # asd

jobs:
  serializing-data:
    if: ${{ github.event.issue.pull_request != null && github.event.comment.body == '/trigger-relevant-data' }}
    runs-on: ubuntu-latest

    steps:
    - name: Serialize and echo github context
      run: |
        echo '${{ toJson(github) }}'
