name: Respond to Trigger Comment

on:
  issue_comment:
    types: [created]  # Trigger when a new comment is created

jobs:
  comment-on-pr:
    if: ${{ github.event.issue.pull_request }}  # Only proceed if the comment is on a pull request
    runs-on: ubuntu-latest

    steps:
      - name: Check for Trigger Phrase
        id: check-trigger
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          if [[ "$COMMENT_BODY" == "trigger-hello-world" ]]; then
            echo "triggered=true" >> $GITHUB_ENV
          else
            echo "triggered=false" >> $GITHUB_ENV

      - name: Post Hello World Comment
        if: ${{ env.triggered == 'true' }}
        run: |
          # Construct the JSON payload for the comment
          JSON_PAYLOAD=$(jq -n --arg body "hello world" '{body: $body}')

          # Post the comment on the PR
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            "${{ github.event.issue.comments_url }}"

      - name: Show completion message
        if: ${{ env.triggered == 'true' }}
        run: |
          echo "Commented: hello world"
