name: 4.2-comment-hello-world-when-specific-comment

on:
  issue_comment:
    types: [created]  # Trigger when a new comment is created

jobs:
  comment-on-pr:
    if: ${{ github.event.issue.pull_request != null && github.event.comment.body == '/trigger-hello-world-comment' }}
    runs-on: ubuntu-latest

    steps:
      - name: Post Hello World Comment
        run: |
          # Construct the JSON payload for the comment
          JSON_PAYLOAD=$(jq -n --arg body "hello world2" '{body: $body}')

          # Post the comment on the PR
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            "${{ github.event.issue.comments_url }}"

      - name: Show completion message
        run: |
          echo "Commented: hello world"