on:
  issue_comment: 
    types:
      - created # blah3

jobs:
  serializing-data:
    if: ${{ github.event.issue.pull_request != null && github.event.comment.body == '/trigger-hello-world-comment' }}
    runs-on: ubuntu-latest
    
    permissions:
      issues: write


    steps:
    - name: Serialize and echo github context
      run: |
        echo '${{ toJson(github) }}'

    - name: debug
      run: |
        echo '123'
        echo ${{ github.event.issue.pull_request }}
        echo ${{ github.event.comment.body  }}
        echo ${{ secrets.GITHUB_TOKEN  }}
        echo ${{ github.event.issue.number  }}
        echo ${{ github.repository  }}
        echo '/trigger-hello-world-comment'
    
    - name: trigger-hello-world-comment
      run: |
        # Get the current time
        CURRENT_TIME=$(date --utc +'%Y-%m-%d %H:%M:%S')

        # Construct the JSON payload for the comment
        COMMENT=$(printf "### Current Time\nThe current time is: %s\n" "$CURRENT_TIME")
        JSON_PAYLOAD=$(jq -n --arg body "$COMMENT" '{body: $body}')

        # Post the comment on the PR
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "$JSON_PAYLOAD" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
        
        
      # curl -L \
      #   -X POST \
      #   -H "Accept: application/vnd.github+json" \
      #   -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #   -H "X-GitHub-Api-Version: 2022-11-28" \
      #   "${{ API_URL }}" \
      #   -d '{"body":"Me too"}'