on:
  issue_comment: 
    types:
      - created # blah3

jobs:
  serializing-data:
    if: ${{ github.event.issue.pull_request != null && github.event.comment.body == '/trigger-hello-world-comment' }}
    runs-on: ubuntu-latest
    
    permissions:
      issues: write

    steps:
    - name: trigger-hello-world-comment
      run: |
        PR_NUMBER=${{ github.event.issue.number }}
        API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
        echo "API_URL=${API_URL}"
        echo "PR_NUMBER=${PR_NUMBER}"
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "${{ API_URL }}" \
          -d '{"body":"Me too"}'
