name: 4.4-comment-hello-space-when-manually-triggered

on: 
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Enter the text to echo'
        required: true

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Serialize and echo github context
        run: |
          echo '${{ toJson(github) }}'

      - name: Post Relevant data Comment
        run: |
          echo "${{ github.event.inputs.pr_number }}"
          echo "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.inputs.pr_number }}/comments" 
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{ "body": "${{ github.repository_owner}} triggered this comment with '${{ github.event.comment.body }}'" }' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.inputs.pr_number }}/comments" 