name: 4.4-comment-hello-space-when-manually-triggered

on: 
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Enter the text to echo'
        required: true

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Serialize and echo github context
        run: |
          echo '${{ toJson(github) }}'

      - name: Post Relevant data Comment
        run: |
          echo "${{ github.event.inputs.pr_number }}"
          echo "https://github.com/${{ github.repository }}/pull/${{ github.event.inputs.pr_number }}" 
        # curl -X POST \
        #   -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        #   -H "Content-Type: application/json" \
        #   -d '{ "body": "hello space" }' \
        #   "https://github.com/robMolloy/workflow-actions-tutorial/pull/9"