name: 5.1-starting-one-workflow-from-another-when-manual-trigger

on:
  workflow_dispatch:

jobs:
  trigger-another-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub Context
        run: echo "${{ toJson(github) }}"

      - name: Trigger another Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const workflow_id = '1.1-echo-hello-world-when-manual-trigger.yml'; // The name of the workflow file
            const ref = 'main'; // Use your branch name
            await github.rest.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id,
              ref,
            });
