name: 6.1-echoing-code-from-a-file-in-a-repo

on:
  push:
    branches:
      - main

jobs:
  display-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display the contents of the readme
        run: |
          cat ./readme.md
