name: 6.2-echoing-code-from-a-newly-created-file-in-a-repo

on:
  push:
    branches:
      - main

jobs:
  display-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a new file
        run: |
          echo "Your text here" > file.txt

      - name: Display the contents of the readme
        run: |
          cat ./file.txt
