name: 7.2-using-output-from-shell-script

on:
  push:
    branches:
      - main

jobs:
  run-shell-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Shell Script
        run: |
          chmod +x ./.github/workflows/scripts/hello-world.sh
          output=$(bash ./.github/workflows/scripts/hello-world.sh)
          short_string=${output:0:5}
          echo "Script Output: $short_string"
