name: 8.1-two-jobs-in-parallel

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print message from Job 1
        run: |
          echo "This is Job 1"
          sleep 2
          echo "This is Job 1"
          sleep 2
          echo "This is Job 1"
          sleep 2
          echo "This is Job 1"
          sleep 2
          echo "This is Job 1"
          sleep 2

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print message from Job 2
        run: |
          echo "This is Job 2"
          sleep 2
          echo "This is Job 2"
          sleep 2
          echo "This is Job 2"
          sleep 2
          echo "This is Job 2"
          sleep 2
          echo "This is Job 2"
          sleep 2

