name: 8.2-waiting-for-jobs-to-finish-before-starting-another

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print message from Job 1
        run: |
          echo "This is Job 1"
          sleep 10
          echo "This is Job 1"
  
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print message from Job 2
        run: |
          echo "This is Job 2"
          sleep 10
          echo "This is Job 2"

  job3:
    runs-on: ubuntu-latest
    steps:
      - name: Print message from Job 3
        run: |
          echo "This is Job 3"
          sleep 10
          echo "This is Job 3"
          
  job4:
    runs-on: ubuntu-latest
    steps:
      - name: Print message from Job 4
        run: |
          echo "This is Job 4"
          sleep 10
          echo "This is Job 4"

  job5:
    needs: [job1, job2, job3, job4]
    runs-on: ubuntu-latest
    steps:
      - name: Print message from Job 3
        run: echo "Job 3 started after Job 1 and Job 2 finished"