name: 8.3-assigning-outputs-from-jobs

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output: "output from job 1"
    steps:
      - name: Print message from Job 1
        run: |
          echo "This is Job 1"
  
  job2:
    runs-on: ubuntu-latest
    outputs:
      output: "output from job 2"
    steps:
      - name: Print message from Job 2
        run: |
          echo "This is Job 2"
  
  job3:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name: Print message from Jobs 1 and 2
        run: |
          echo "Job 3 started using output from jobs 1 and 2: ${{ needs.job1.outputs.output }} ${{ needs.job2.outputs.output }}"
