name: 8.4-reassigning-outputs-from-jobs

on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.step1.outputs.output }} 
    steps:
      - name: Print message from Job 1
        id: step1
        run: |
          echo "This is Job 1"
          echo "output=new output from job 1" >> $GITHUB_OUTPUT
  
  job2:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.step2.outputs.output }} 
    steps:
      - name: Print message from Job 2
        id: step2
        run: |
          echo "This is Job 2"
          echo ${{ toJson(steps) }}
          echo "output=new output from job 2" >> $GITHUB_OUTPUT
  
  job3:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name: Print message from Jobs 1 and 2
        run: |
          echo "Job 3 started using output from jobs 1 and 2: ${{ needs.job1.outputs.output }} ${{ needs.job2.outputs.output }}"
